### ISSUE TITLE
eaf3d.c not compatible with MSVC due to using VLAs

### ISSUE THREAD

**Issue by FergusRooney** [auto-optimization/eafpy#12]
EAF3d uses VLA which are not supported by MSVC  windows compiler - see [here](https://github.com/auto-optimization/eafpy/blob/8170e7333eebb1cea97d191368fa7a61c06c864a/src/eafpy/libeaf/eaf3d.c#L552). This means that the eaf C function will not compile on windows.
The options are either:
1. Change eaf3d.c to use dynamic allocation instead of VLA. I have started some work on this but it is not working [this branch](https://github.com/auto-optimization/eafpy/tree/dynamic_eaf3d)
2. Change windows compiler to MinGW32. I have had some success with this, however I cannot work out how to conditionally change the compiler, so this will not work on linux. The compiler is selected in [this setup.cfg file](https://github.com/auto-optimization/eafpy/blob/fb1571a3750254f1c47a4b454e0edb46511b144a/setup.cfg#L1). Also, I am getting slightly different results when calculating a 3d eaf in  MINGW32 version compared to Linux GNU GCC version

**Comment by MLopez-Ibanez** [comment]
Fixed by [79f076f](https://github.com/auto-optimization/eafpy/commit/79f076fcecfdaa5107bf36e5870555f121e255b4)
